{% set name = "ipython-autotime" %}
{% set version = "0.2.0" %}
{% set sha256 = "07172d41be6e8b15732b7f3c492a42183f5aa88ba875e34a6c422b083ca93321" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
    - autotime

about:
  home: https://github.com/cpcloud/ipython-autotime
  license: MIT
  license_file: LICENSE
  license_family: MIT
  # license_file: LICENSE # When added to MANIFEST.in – https://github.com/cpcloud/ipython-autotime/pull/6
  summary: Time everything in IPython
  dev_url: https://github.com/cpcloud/ipython-autotime

extra:
  recipe-maintainers:
    - proinsias
