{% set name = "ipython-autotime" %}
{% set version = "0.3.0" %}
{% set sha256 = "6a3fd5c33d092326be4a8c24d806f5a45387d94b1f8216ee2b5fc691d47b211a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - ipython

test:
  imports:
    - autotime

about:
  home: https://github.com/cpcloud/ipython-autotime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Time everything in IPython
  dev_url: https://github.com/cpcloud/ipython-autotime

extra:
  recipe-maintainers:
    - proinsias
